spring:
    datasource:
        password: postgres
        url: jdbc:postgresql://docker-postgres:5432/ze_db
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
        show-sql: true
