spring:
    datasource:
        password: postgres
        url: jdbc:postgresql://docker-postgres:5432/ze_db
        username: postgres
    jpa:
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false

